name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-app/backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        
    - name: Build with Maven
      run: cd portfolio-app/backend && mvn clean package -DskipTests
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portfolio-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'portfolio-app/backend/target/*.jar'
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: portfolio-app/backend/target/*.jar 