name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-app/backend/**'
      - '.github/workflows/backend-deploy.yml'

permissions:
  id-token: write        # allow azure/login to fetch the OIDC token
  contents: read         # allow checkout to read your code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        
    - name: Build with Maven
      run: cd portfolio-app/backend && mvn clean package -DskipTests
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy with Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          az webapp deploy \
            --resource-group rg-portfolio \
            --name portfolio-api-app \
            --src-path portfolio-app/backend/target/*.jar
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: portfolio-app/backend/target/*.jar 
