name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-app/backend/**'
      - '.github/workflows/backend-deploy.yml'

permissions:
  id-token: write        # allow azure/login to fetch the OIDC token
  contents: read         # allow checkout to read your code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        
    - name: Build with Maven
      run: cd portfolio-app/backend && mvn clean package -DskipTests
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'portfolio-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'portfolio-app/backend/target/*.jar'
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: portfolio-app/backend/target/*.jar
