name: Deploy Redirector to Azure Static Web App

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-app/redirector/**'
      - '.github/workflows/redirector-deploy.yml'

jobs:
  deploy-redirector:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Deploy Redirector to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_PLANT_0CE0F1C0F }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "portfolio-app/redirector"
        api_location: ""
        output_location: ""
        skip_deploy_on_missing_secrets: false 